#!/usr/bin/env zsh

brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if (($brightness > 1)); then
  let brightness=$brightness-50
  if (($brightness < 1)); then
    brightness=1
  fi
  echo $brightness > /sys/class/backlight/intel_backlight/brightness
fi
