#!/usr/bin/env zsh

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)
brightness=$(cat /sys/class/backlight/intel_backlight/brightness)

if (($brightness < $max_brightness)); then
  let brightness=$brightness+50
  if (($brightness > $max_brightness)); then
    brightness=$max_brightness
  fi
  echo $brightness > /sys/class/backlight/intel_backlight/brightness
fi
