#!/bin/zsh

# install AWS CLI like this:
# ➭ sudo pip install awscli
#
# create user screener in AWS IAM with write permission to s3
# and write credentials to ~/.aws/credentials in section "[screener]"
#
# create bucket on aws s3 likte this:
# ➭ aws --profile screener s3api create-bucket --bucket mentoscreen
#
# make CNAME from i.mne.li to i.mne.li.s3.amazonaws.com

#pk=$(pkill -c gnome-screenshot)
#
#if [[ $pk > 0 ]]; then exit; fi

me_rand (){
  cat /dev/urandom | tr -dc '0-9a-zA-Z' | head -c$1
};

fname=$(me_rand 8)".png"
addr="http://i.mne.li/$fname"

mkdir -p ~/tmp/screens/;

#import ~/tmp/screens/$fname
gnome-screenshot -a --file=$HOME/tmp/screens/$fname

#if [[ -e ~/tmp/screens/$fname ]]; then
#  aws s3 --profile screener cp ~/tmp/screens/$fname s3://i.mne.li --acl public-read
#  #scp ~/tmp/screens/$fname d.mne.li:/var/caddy/sharer/;
#  echo -n $addr | xclip;
#  xdg-open $addr
#fi

