#!/bin/zsh

me_rand (){
  cat /dev/urandom | tr -dc '0-9a-zA-Z' | head -c$1
};

fname=$(me_rand 8)".png"
addr="http://d.mne.li/$fname"

mkdir -p ~/tmp/screens/;

import ~/tmp/screens/$fname
scp ~/tmp/screens/$fname d.mne.li:/tmp/sharer/;
echo -n $addr | xclip;
xdg-open $addr


