#!/bin/zsh

# run docker like this on server:
# mkdir -p /tmp/sharer && echo '' > /tmp/sharer/index.html && docker run -d -p 80:80 -v /tmp/sharer:/sharer python /bin/bash -c "cd /sharer && python3 -m http.server 80"

pk=$(pkill -c import)

if [[ $pk > 0 ]]; then exit; fi

me_rand (){
  cat /dev/urandom | tr -dc '0-9a-zA-Z' | head -c$1
};

fname=$(me_rand 8)".png"
addr="http://d.mne.li/$fname"

mkdir -p ~/tmp/screens/;

import ~/tmp/screens/$fname

if [[ -e ~/tmp/screens/$fname ]]; then
  scp ~/tmp/screens/$fname d.mne.li:/tmp/sharer/;
  echo -n $addr | xclip;
  xdg-open $addr
fi

