#!/usr/bin/env perl

use warnings;
use strict;

my $state = `xset q | grep 'Monitor is'`;

chomp $state;
$state =~ s/^\s*//;

if ( $state eq 'Monitor is On' ) {
  `xset dpms force off`;
} else {
  `xset dpms force on`;
}

