#!/usr/bin/env perl

use warnings;
use strict;

for my $module ( @ARGV ) {
  my $package = $module;

  # From This::That to This/That.pm
  s/::/\//g, s/$/.pm/ for $module;

  eval {
    require $module;
  };

  if ($@) {
    print "Cant find in:\n";
    for my $path (@INC) {
      print "$path\n";
    }
  } else {
    print $package . " => " . $INC{$module} . "\n";
  }
}

