#!/usr/bin/zsh

#$lim=''

if [ "$1" -gt 0 ]; then
  LIM="LIMIT $1"
else
  LIM=""
fi

sqlite3 ~/.Skype/debo.on/main.db "SELECT case when c.topic is null then c.friendlyname else c.topic end, datetime(l.timestamp, 'unixepoch', 'localtime') as timestamp, l.from_dispname, l.body_xml FROM skypelog l LEFT JOIN Messages m ON l.timestamp = m.timestamp and l.body_xml = m.body_xml LEFT JOIN Chats c on l.chatname = c.name WHERE m.timestamp is null order by timestamp $LIM;" | perl -MHTML::Entities -ne 'print decode_entities($_)' | column -t -s '|'

#sqlite3 ~/.Skype/debo.on/main.db "SELECT case when c.topic is null then c.friendlyname else c.topic end, datetime(l.timestamp, 'unixepoch', 'localtime'), l.from_dispname, l.body_xml FROM skypelog l LEFT JOIN Messages m ON l.timestamp = m.timestamp and l.body_xml = m.body_xml LEFT JOIN Chats c on l.chatname = c.name;"
