#!/usr/bin/zsh

sqlite3 ~/.Skype/debo.on/main.db "CREATE TABLE skypelog (chatname TEXT, author TEXT, from_dispname TEXT, timestamp INTEGER, body_xml TEXT);"
sqlite3 ~/.Skype/debo.on/main.db "CREATE TRIGGER update_skypelog AFTER UPDATE ON Messages BEGIN INSERT INTO skypelog SELECT new.chatname, new.author, new.from_dispname, new.timestamp, new.body_xml WHERE (SELECT count(*) FROM skypelog WHERE timestamp = new.timestamp AND body_xml = new.body_xml) = 0; END;"

