#!/usr/bin/env perl

use warnings;
use strict;

my $fHigh = `synclient -l | grep 'FingerHigh' | sed 's/.* = \\([[:digit:]]*\\)\$/\\1/'`;
my $fLow = `synclient -l | grep 'FingerLow' | sed 's/.* = \\([[:digit:]]*\\)\$/\\1/'`;

chomp $fHigh;
chomp $fLow;

if ( $fHigh eq '' && $fLow eq '' ) {
  exit;
}

if ( $fHigh-5 > $fLow ) {
  my $toSet = $fLow+5;
  `synclient FingerHigh=$toSet`;
  #print "toSet = '$toSet'";
} else {
  `synclient FingerHigh=255`;
}

#print "High = '$fHigh', Low = '$fLow'\n";

